# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('query', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
